### ISSUE TITLE
complete Ideation deliverables

### ISSUE THREAD

**Issue by realmikkifriend** [realmikkifriend/ist#1]
# User Stories

1. **As a developer, I want a clear vision of the app I'm building**

    - _Scenario:_ As I build this app, I want clear, specific guidelines regarding scope and goals.
    - _Acceptance Criteria:_ There should be sufficient strategy and design documents to guide the development process:
        - Strategy document
        - User Personae

### Out of Scope

Because this is a rebuild of a previous app, I won't create wireframes.

# Resources & Deliverables

- Strategy document
- User personae
    - neurodivergent user
    - new user

# Tasks

- [x] adapt previous documents to new project ①
    - [x] complete introduction
    - [x] read over partially finished strategy template, create initial issues and tasks
    - [x] write out justification for skipping wireframes
- [x] complete user research and deliverables 3dd45e2 ②
    - [x] create New User persona file (`persona-new.md`) ①
        - [x] link from Strategy file
        - [x] write up New User summary in Strategy file
    - [x] create Neurodivergent User persona file (`persona-nd.md`) ①
        - [x] link from Strategy file
        - [x] write up Neurodivergent User summary in Strategy file
    - [x] write up needs analysis
- [x] complete project proposal ⑤ 14714fe
    - [x] complete problem/solution sections 01000d2
        - [x] write up problem statement
        - [x] write up Octalysis analysis ③
    - [x] complete analysis section ① cc5d574
        - [x] complete competitive analysis (SWOT)
        - [x] complete risk assessment
    - [x] complete last sections with machine assistance ①
        - [x] write up functional requirements
        - [x] write up brief stakeholders section
        - [x] write out technical and resource requirements
        - [x] write out evaluation and success measures
        - [x] write up introductory summary paragraph
