### ISSUE TITLE
complete Project Planning deliverables

### ISSUE THREAD

**Issue by realmikkifriend** [realmikkifriend/ist#3]
# User Stories

1. **As a developer, I want to refer to specific plans during development**

    - _Scenario:_ As I develop this app, I want to always know what specific features and tasks must be completed next.
    - _Acceptance Criteria:_ There should be a clear roadmap of tasks to complete.

### Out of Scope

# Resources & Deliverables

- [User story map of MVP](https://github.com/realmikkifriend/ist/blob/main/strategy/usm-mvp.png)
- Estimation matrix

## Story Points Estimation Matrix
| # | ◯ | Effort | Time | Complexity | Risk & Uncertainty |
| --- | --- | --- | --- | --- | --- |
| 0 | — | quick reminder | minutes | simple | none |
| 1-2 | ①② | minimum effort | 1-2 hours | simple | none |
| 3 | ③ | Effort | half day | a little complex | slight |
| 5 | ⑤ | Focused Effort | full day | somewhat complex | moderate |
| 8 | ⑧ | Sustained Effort | multiple days | complex | moderate |
| 13 | ⑬ | Epic | sprint | highly complex | risky & uncertain |

# Tasks

- [x] complete MVP user story map, link from project proposal ② 3f8524f
- [x] read over Strategy Deliverables notes, determine what to complete
- [x] fill out #6 ①
- [x] complete story points estimation ①
    - [x] add estimation matrix to Resources & Deliverables above
    - [x] link to estimation matrix from issue template
- [x] estimate points for #6
