### ISSUE TITLE
deploy MVP

### ISSUE THREAD

**Issue by realmikkifriend** [realmikkifriend/ist#6]
# User Stories

1. **As a user, I want to learn about the app, log in, and interact with elements.**

    - _Scenario:_ I want to view an informative front page, log in using Todoist, and interact with tasks and comments.
    - _Acceptance Criteria:_ All User Tasks in the user story map are implemented.

### Out of Scope

Anything not listed in the user story map.

# Resources & Deliverables

- [User story map of MVP](https://github.com/realmikkifriend/ist/blob/main/strategy/usm-mvp.png)
- [estimation matrix](https://github.com/realmikkifriend/ist/issues/3)

# Tasks

- [x] set up dev stack (Node, Svelte, Tailwind+DaisyUI) ① 5521f5c
    - [x] implement Tailwind and DaisyUI 8bda3c5
- [x] user can authorize Todoist ③ b40272a
    - [x] write up bare-bones front page with log-in button
    - [x] implement auth workflow, set access token
    - [x] detect access token and logged-in status
- [x] get list of due tasks, display a single task ③ 1449c2d
- [x] set up persistent store ② 06165cb 
- [x] refresh display when data updated ③
    - [x] add toasts, notify user if data updated ① e2a895e
    - [x] ask to load different task ② 70532b5
- [x] update task sort function to integrate priority ① a5957ce
- [x] user can mark task done ②
- [x] implement sidebar with list of contexts ① cd7e580
- [x] add context selection, reflect in single task shown ②
- [x] update visual styles ①
    - [x] change body font
    - [x] change color palette
    - [x] add favicon
    - [x] responsive on mobile
- [ ] set up continuous deployment ③

### Out of MVP Scope
- user can defer tasks
- UX fine-tuning
    - debug flash of regular first `dueTask` 
    - unset store if updated over 1 hour ago (prevents showing outdated data)
- display skeletons while loading
- show count and priorities in context card
- next to menu icon, if context selected, show pill with context name, x to unset
- add different sorting methods to sidebar
    - add settings toggle to top of sidebar
    - add options to group by context (default) or priority
    - keep setting in store
    - changing setting triggers re-sorting list
        - sorting function accesses setting in store
        - suppress warning about updating current task display
    - reflect setting in contexts list
- display task comments
- user can authorize Dynalist
- display basic interactive checklists
